server:
  port: 29110
logging:
  config: classpath:logback-spring.xml
spring:
  redis:
    redisson:
      # 使用config配置 需要在config后加一个 | 参考https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter
      # 使用config配置 指定spring.redis.redisson.codec 需要加双引号 使用file则不需要加双引号
      file: classpath:redisson-single-template.yml
dcredis:
  config:
    nameSpace: service-id